### ISSUE TITLE
Suricata Support

### ISSUE THREAD

**Issue by JonZeolla** [Netflix/Fido#8]
Is there any intent to provide Suricata support in addition to Snort?

**Comment by robfry** [comment]
I would love to do Suricata! It's not something I've had access to in the past. The array of integrations I currently have are based on partnerships, friendships, or access to them because we purchased the product from the vendor. In the past we used Sourcefire/Snort, which is why I have a remedial connector built, but Suricata support is very doable. One of the intentions of open sourcing FIDO would be to continue to build out a library of integrations to make it more relevant.

**Comment by JonZeolla** [comment]
I would be interested in helping out where I can.  We're an open source shop and this has the potential to help us out in multiple ways.
